### ISSUE TITLE
Not enough gas

### ISSUE THREAD

**Issue by vgrichina** [near-examples/pow-faucet#72]
Trying to create account gives following error:

```
{"jsonrpc":"2.0","error":{"code":-32000,"message":"Server error","data":{"TxExecutionError":{"InvalidTxError":{"ActionsValidation":{"TotalPrepaidGasExceeded":{"total_prepaid_gas":10000000000000000,"limit":300000000000000}}}}}},"id":135}
```

**Comment by evgenykuzyakov** [comment]
The code attaches more than the max prepaid limit. Since the code is old, then either the default is `10000 TGas` or it's somewhere in the API.

Probably we should upgrade to the latest `near-api-js`

**Comment by vgrichina** [comment]
Fixed here https://github.com/near-examples/pow-faucet/commit/5d4de8fa5d81331becc7011c820b01845d75f588
